ryanmcdermott/clean-code-javascript

README.md

Property title is assigned to property buttonText.

Some minor property missmatch

---

README.md

Hey there. As a Software Engineer who happens to be Nigerian, I think there are better ways of explaining a side effect than perpetuating stereotypes about a specific group of people. So I just made a small fix to make it more appropriate.

Update README.md to remove Nigerian Prince reference

---

README.md

(ES6) When you declare a constant, the variable should stay the same throughout the program.

Use constants when variable values do not change

---

README.md

Use `console.error` at least as `console.log` essentially turns a thrown error into a muted console log.

Update: promise catch logic

---

README.md

per preceding rule "ES6 constants when variable values do not change"

use const in rule "Use explanatory variables"

---

README.md

It's just a quick adjust in the "Set default objects with Object.assign" section where the results on the comment show de result after assign new attributes into the object.

Adjusted the comment that show the result

---

README.md

As discussed in #31 here my implementation of `const` and `let`.

Change var and let where necessary

---

README.md

In the section "Functions should do one thing" this change uses
the Array.filter method to get the active clients, then emailing
those with the forEach loop.

Improvement on email client function

---

README.md

Here's a preview of [jsinspect](https://github.com/danielstjules/jsinspect) output when ran on the example.

Add mention of jsinspect for duplicate code detection

---

README.md

The save method isn't returning this, so the car variable
is equal to undefined instead of a Car object.
BTW, Thanks alot for this guide.

return true on save method to continue chaining

---

README.md

Something looked off about this so I did a quick check in node.
You must have been distracted at the time of writing :)

fix output in Object.assign() example

---

README.md

the old code throws a ReferenceError exception

use this to access object methods

---

README.md

from 6 to 4 in Function callers and callees should be close

Fix indentation in code

---

README.md

replace accidental tabs by spaces

---

README.md

comment out all the ellipses consistently

---

README.md

fix new cases with const and let

---

README.md

See [no-shadow](http://eslint.org/docs/rules/no-shadow).

fix variable shadowing

---

README.md

use assignment operators

---

README.md

(This commit also deletes a redundant `else`.)

replace == with ===

---

README.md

fix a brace style inconsistency

---

README.md

use single quotes consistently

---

README.md

1. Add function name if it can't be inferred from the context. See [func-names](http://eslint.org/docs/rules/func-names).
2. Replace anonymous functions with arrow functions when appropriate. See [prefer-arrow-callback](http://eslint.org/docs/rules/prefer-arrow-callback).
3. Replace anonymous functions with method shorthand notation when appropriate. See [object-shorthand](http://eslint.org/docs/rules/object-shorthand).
4. Remove a redundant IIFE. Fixes #30 temporarily.

address anonymous functions

---

README.md

replace string concatenation by template literals

---

README.md

parenthesize arrow function arguments consistently

---

README.md

Improve example to be more consistent and remove unneeded context

Improve example "Function names should say what they do"

---

README.md

1.  Use object shorthand notation.
2.  Remove default constructors (see http://eslint.org/docs/rules/no-useless-constructor).
3.  Use functional Array methods instead of cycles and intermediate structures.
The third change also excludes hidden type coercion from array elements comparing.
Using the previous example:
```js
/******************************************************************************/
'use strict';
/******************************************************************************/
class SuperArray extends Array {
constructor(...args) {
super(...args);
}
diff(comparisonArray) {
var values = [];
var hash = {};
for (var i of comparisonArray) {
hash[i] = true;
}
for (var i of this) {
if (!hash[i]) {
values.push(i);
}
}
return values;
}
}
const sa = new SuperArray(1, 2, 3); …
```

Simplify some code examples

---

README.md

lookupManager method was written as lookupMananger()

Fix lookupManager typo

---

README.md

Modify open/closed principle

---

README.md

Animal->Human
into
Human->Animal
because Human **is a** Animal

fix is-a order in Prefer composition over inheritance description

---

README.md

Fix issue #130

---

README.md

Regarding #108. Is the example clear?

Add Side Effects pt.2

---

README.md

`cart` is an Array. the ES6 spread operator can be used : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator

Immutable error

---

README.md

Changed Function arguments section to include destructuring

---

README.md

Added _this_ to verifyIfAmountCanBeSetted otherwise you get ReferenceError

Fix method call in getter/setter example

---

README.md

**Pedal** is the act of using bicycle pedals. *Peddle* means to travel around selling something. I think you meant the former.
BTW, thanks for the great guide!

README.md: change 'peddle' to 'pedal'

---

README.md

The assertion should be same as others.

Update the example from "Single concept per test"

---

README.md

As mentioned in #175, `showEmployeesList()` now [says what it does](https://github.com/AnnaNee/clean-code-javascript#function-names-should-say-what-they-do).

Explicit function name

---

README.md

Fixes some typo and logic issues

Fixes some typo issues

---

README.md

Hello! I added second translation to Russian. It was my promise [here](https://github.com/ryanmcdermott/clean-code-javascript/issues/148#issuecomment-274264014). It is relevant for today.

Adds second and actual russian translation

---

README.md

Use ES6 style imports instead of require

---

README.md

fix: code style

---

README.md

Like their site title,
AngularJS not Angular.js
Reference: https://angularjs.org/

fix angularjs typing

---

README.md

currently translating it all to spanish.

added spanish translation

---

README.md

In the Bad section, shouldn't it be config.cancellable !== undefined?

Mistake in the Set default objects with Object.assign

---

README.md

...you will find that those **case**... -> ..you will find that those **cases**...

fixed a grammatical typo

---

README.md

The example for removing the duplicate code would not work because the getGithubLink() is not a function of the manager object, which would cause an error.

Fix duplicate code example

---

README.md

updating function name per #200 thanks to @marzelin to clean up some issues

Update README.md to include explanatory function names per #200

---

README.md

I have just completed the Polish translation, please add my link to the list.
- Related:
Want to translate to Arabic, Japanese, French, etc.? #148

Add Polish translation

---

README.md

Capital letters in const, remove default data in class Car

Capital letters in const, remove default data in class Car

---

README.md

Remove space before colon in object.

Object style consistency

---

README.md

There is a difference between the bad example and the good in the "Favor functional programming over imperative programming" section. The good one (functional) acts like two **for**s: the first with the creation of the new array and the second with the summing.
But you could use a object destructuring, which you recommend in the previous section, instead of using map method.
Also the use of INITIAL_VALUE makes sense now :)

Replace map method with object destructuring

---

README.md

minor grammar edit

---

README.md

This distracted me from the code at hand, so I suggest changing the text to be more neutral.

remove distracting reference in "testing single concept per test"

---

README.md

Added traditional chinese  finally. 🎉🎉🎉

Added link to the traditional chinese translation 

---

README.md

My ongoing work is on develop branch.

Added source link for bengali translations

---

README.md

I added one advantage and one bad example in function parameters.

Add advantage in function parameters

---

README.md

- sort translations
- add Armenian to the list, closes #241

translations

---

README.md

"PER" has the same meaning as "IN_A" but is less verbose

Make example more succinct

---

README.md

I've added a Persian translation to the list. It can help people who are speaking Persian or Farsi from all around the world to write cleaner code in Javascript.

Persian translation added (Fluent + RTL styled)
