README.md
Just some corrections on spelling and minor formatting.
=> (docs) Correct spelling errors and remove unfinished sentence.

README.md
Without this, the `shape.getArea()` call below will cause an error.
=> Add getArea method where it is necessary.

README.md
In the "good" `Object.assign` example, the initial new object is redundant as the defaults are also specified in a new object.
This is a bit pedantic, and doesn't change the semantics of the example, just removes an unnecessary object creation.
*Note:* I definitely wouldn't have bothered with this if I didn't make #4, and was looking at it anyway 😄
=> Remove redundant object from Object.assign example

README.md
Addresses #52.
I applied your format suggestion to stay consistent over the whole document.
=> Mention async functions as part of ES2017 instead of ES7 (ES2016)

README.md
`Fewer` should be used for countable objects.
https://en.wikipedia.org/wiki/Fewer_vs._less
=> Corrects usages of less for fewer

README.md
https://github.com/danielstjules/buddy.js is a tool that exists to identify magic numbers. Here's the result of running the example in the readme:
Here's another example from the buddy.js readme:
I also mention eslint, which added a magic number rule based on buddy.js in https://github.com/eslint/eslint/blob/660e0918933e6e7fede26bc675a0763a6b357c94/lib/rules/no-magic-numbers.js#L2 Not sure if it handles the same test cases, but it's the only general linter I know of that detects these things.
=> Mention tools for identifying magic numbers

README.md
See [no-use-before-define](http://eslint.org/docs/rules/no-use-before-define).
Class declarations are not hoisted. So ['keep the caller right above the callee' rule](https://github.com/ryanmcdermott/clean-code-javascript#function-callers-and-callees-should-be-close) is less applicable here. Though the order of calls mitigates the danger of errors here, maybe in such a normative tip list this should be considered.
=> reorder class declarations

README.md
=> add `break` statement to prevent erroneous fall-through

README.md
See: http://eslint.org/docs/rules/class-methods-use-this
This commit adds using of `this`, deletes abundant arguments or inserts explicit ellipses (the last two fixes imply using of `this`).
Also, it corrects some indentation cases.
=> correct using of `this` in examples

README.md
Based on the **Error Handling** section.
I think good example should all use `console.error` to deal with error messages.
=> Fix one code exsample use `console.log` to print error

README.md
- The original document asserted that "Short-circuiting is cleaner than conditionals"
- ...only to override this assertion later with "Use default arguments instead of short circuiting."
- This is a poor design-choice for an advisory document.
- If you are going to say x > y,
- then later say z > x,
- you should just say z > x > y upfront.
- Otherwise, many people might not see the z > x later on,
- because many people will probably use this as a referential document. They probably won't read the entire work.
=> Rephrase default value advice

README.md
This use the ES2015 way.
I removed the match because it's not used and we could also declare a const all to grab the first item of the match if needed.
=> Use destructuring for explanatory variables

README.md
This example should follow the guidelines about `const` vs `var` mentioned earlier
=> Use const instead of var

README.md
Fixed few lines by adding missing semicolons.
=> Fixed few examples

README.md
Assuming that waiting 1/1000 of a day was not intended.
Second parameter of setTimeout() is in milliseconds (https://developer.mozilla.org/en-US/docs/Web/API/WindowTimers/setTimeout).
=> "Use searchable names" and correct unit of time

README.md
Add missed semicolons.
Comment out ellipses.
Use object shorthand.
Delete block padding.
Delete default constructors.
(With [this script's](https://github.com/ryanmcdermott/clean-code-javascript/issues/113) results.)
=> fix new instances of previously fixed cases

README.md
See [the comment](https://github.com/ryanmcdermott/clean-code-javascript/pull/65#issuecomment-272082413) of @ryanmcdermott.
With this PR:
1. Bad and old examples become more comparable (let bad examples be bad only in regard to one appropriate case).
2. Both examples do not contain type coercion (i.e. they use strict comparing).
3. The new algorithm has less performance difference in small and large arrays comparing (some benchmarks have been done).
=> make bad and old examples more comparable

README.md
Pretty minor. But destructuring state using the regex was a little bit ambiguous since there is no state in the address (zip code instead).
=> Rename state to zipCode to avoid confusion

README.md
Great resource!
Here's a fix for something I noticed in the `async/await` example. There's no need to `await` a call to `require`, and they might sooner be written in single lines to mimic the style used for the previous examples. I might have overlooked something though, if so, let me know!
=> fix async/await example

README.md
There is no need to create an arrow function to execute a function inside of the timeout.
=> Simplify "Use searchable names" example

README.md
Add translation section in the same format of AirBnb style, with Brazilian Portuguese and Chinese translations.
I"m unable to tell the difference between "Traditional" and "Simplified" Chinese as AirBnb did in their translations, perhaps someone can help with this distinction.
Also, fix a minor markdown error.
=> Add translations section + fix minor typo md error

README.md
I didn't know what was the second argument of `reduce` function and I had to look for it.
I think that now it's more clear.
=> Change literal for a constant

README.md
Function constructors should be avoided. Using the `this` keyword will increase the risk for bugs. An example: if not using the `new` keyword when creating an instance of the Employee object, `this` will be bound to the global object, and not to the Employee instance.
Use a maker function instead, returning an object, using variables existing in the scope of the function (closure).
=> Maker function instead of Function constructor

README.md
The good example of the Liskov Substitution principle in the SOLID section is doing a switch case to set the width/height/length of the shapes. I think they should accept parameters on instantiation. Lot's of code can be deleted: the switch clause and all setters for width/height/length. Less code!
=> Liskov Substitution (SOLID section) - width/height/length as constructor params

README.md
The "Use getters and setters" section describes that it is hard to enforce the pattern, because JavaScript don't have the public and private keywords. I think this is actually an issue with JavaScript classes. With functions, properties can easily be private.
Described in https://github.com/ryanmcdermott/clean-code-javascript/issues/180
=> getters and setters as functions, also without the get/set keywords

README.md
Fixed a mismatch between bad & good example that cause a distraction. That's in `Function callers and callees should be close` section.
=> fixed a mismatch between bad-good example

README.md
The proposed "good" way of coding was actually changing a property's name in the developers object.
While one can argue that in this case they could be the same, the point of the example was to show that you can still remove duplicated code that require *different* things.
=> Fixed duplicate code

README.md
It doesn't need to be a global constant. JavaScript constants are block-scoped.
=> Fix "Use searchable names" section

README.md
Like said in https://github.com/ryanmcdermott/clean-code-javascript#function-callers-and-callees-should-be-close, the code is read from top to bottom, so I'd prefer the definition of the *function parseBetterJSAlternative* above the functions called within.
=> Changing order in example of *Functions should only be one level …*

README.md
Unnecessary Array.prototype.map method.
=> remove map method in favor functional programming

README.md
Enjoyed reading this article! Some slight suggestions: 
- rename ast variable to be more explicit (see, Avoid Mental Mapping)
- rename function lexer to include a verb in it's name (see,
https://herbertograca.com/2016/09/03/clean-code-3-functions-by-robert-c-martin-uncle-bob/)
- from my understanding, the term lexer is usally used for the
process of building a stream of tokens. So lexer and tokenize are
different names for the same thing
=> improve "Functions should only be one level of abstraction" example

README.md
Added Spanish translation finally! :tada:
=> Added link to the new spanish translation

README.md
Hello Ryan,
Thank for your guide. Enjoying reading it.
I have noticed that http links on this guide are https compatible so I updated all of them to htttps.
- https://www.osnews.com/images/comics/wtfm.jpg
- https://gotwarlost.github.io/istanbul/
- https://jstherightway.org/#testing-tools
- https://standardjs.com/rules.html
Cheers 💪
=> Update plain http links to https

README.md
`const MILLISECONDS_IN_A_DAY = 86_400_000;`
We can use numeric separator with 
https://babeljs.io/docs/en/babel-plugin-proposal-numeric-separator
=> Added numeric separator for improve readability

README.md
Hey,
I think it's a bit more clear like that. WDYT?
Also there was a little typo because `86_400_000` is not a number.
=> Add calculation for milliseconds in a day

README.md
Fix a typo related to issue #321
=> Fix stray hyphen turning into a random bullet

README.md
=> Fix wrong naming of `default parameters`
